import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Store } from '../packages/storage.ts';
import { configSchema } from '../packages/config.ts';
import { PersonaService } from '../packages/persona/service.ts';
import { definitionSchema } from '../packages/persona/contracts.ts';
import { personaGenerationInput, type GenerationRequest, type PersonaGenerator } from '../packages/persona/generator.ts';

const config=configSchema.parse({database:':memory:',ai:{provider:'openai_api'}});
function fixtureDefinition(request:GenerationRequest){return definitionSchema.parse({schema_version:1,persona_id:request.persona_id,definition_version:1,template_revision_id:request.template.template_revision_id,locale:request.locale,display_name_suggestion:`Viewer ${request.persona_id.slice(0,5)}`,core:{viewing_motive:request.template.behavior_family,interests:[request.planning_brief.topic],disinterest:['repeated context'],observation_focus:['visible changes'],temperament:'Calm and curious',social_behavior:'Responds to other viewers with care'},knowledge:[{topic:request.planning_brief.topic,level:'basic',boundary:'Uses only directly available information'}],voice:{register:'casual',typical_length:'short',punctuation_tendency:'concise',laughter_tendency:'rare',allowed_variation:['observation'],avoid:['unsupported certainty']},participation:{base_propensity:0.3,topic_sensitivity:0.7,reply_propensity:0.2,speak_when:['new information appears'],stay_silent_when:['context is unclear']},examples:[{situation:'a visible outcome changes',action:'send',text:'Generated contribution A'},{situation:'unclear background',action:'skip'},{situation:'new detail appears',action:'send',text:'Generated contribution B'},{situation:'nothing changes',action:'skip'}],negative_examples:[{situation:'a past event',unacceptable_behavior:'claiming to have watched it'},{situation:'a private plan',unacceptable_behavior:'claiming hidden knowledge'}]});}
async function waitJob(service:PersonaService,id:string){for(let i=0;i<100;i++){const job=service.job(id);if(job.status!=='queued'&&job.status!=='running')return job;await new Promise(r=>setTimeout(r,5));}throw Error('job timeout');}

test('persona generation uses provider-created cards and never sends private production context',async()=>{
  const store=new Store(':memory:');store.ingestBatch([{platform:'youtube',channel:'c',author:'u',name:'Viewer',text:'hello'}]);
  const requests:GenerationRequest[]=[];const generator:PersonaGenerator=async(request)=>{requests.push(structuredClone(request));const definition=fixtureDefinition(request);definition.examples[0]={situation:'a visible outcome changes',action:'send',text:`Generated contribution ${request.persona_id}`};return{definition,inputTokens:100,outputTokens:200};};
  const service=new PersonaService(store,undefined,config,generator);const session=service.createBrief({session_title:'Test broadcast',topic:'Puzzle game',audience_intent:'Observe and react',public_context:'The audience can see the puzzle.',private_production_context:'secret phrase ORCHID-VAULT-DELTA',tone_policy:'Be natural',candidate_count:2,cast_size:1});
  const queued=service.createCandidates(session.id);const job=await waitJob(service,queued.id);assert.equal(job.status,'succeeded');assert.equal(job.result.length,2);assert.equal(requests.length,2);assert.equal(JSON.stringify(requests).includes('ORCHID-VAULT-DELTA'),false);assert.equal(JSON.stringify(job.result).includes('secret phrase'),false);assert.notEqual(job.result[0].definition.examples[0].text,job.result[1].definition.examples[0].text);assert.equal(job.result[0].provenance.generator,'openai_api');const providerPayload=JSON.stringify(personaGenerationInput(requests[0]));assert.equal(providerPayload.includes(requests[0].persona_id),false);assert.equal(providerPayload.includes(requests[0].template.template_revision_id),false);
  store.close();
});

test('persona generation rejects private context echoed by provider output',async()=>{
  const store=new Store(':memory:');store.ingestBatch([{platform:'youtube',channel:'c',author:'u',name:'Viewer',text:'hello'}]);
  const generator:PersonaGenerator=async(request)=>{const definition=fixtureDefinition(request);definition.core.viewing_motive='I know ORCHID-VAULT-DELTA';return{definition};};
  const service=new PersonaService(store,undefined,config,generator);const session=service.createBrief({session_title:'Test broadcast',topic:'Puzzle game',audience_intent:'Observe and react',public_context:'The audience can see the puzzle.',private_production_context:'secret phrase ORCHID-VAULT-DELTA',tone_policy:'Be natural',candidate_count:1,cast_size:1});
  const queued=service.createCandidates(session.id);const job=await waitJob(service,queued.id);assert.equal(job.status,'failed');assert.deepEqual(service.listCandidates(session.id),[]);
  store.close();
});

test('persona approval, frozen cast, policy revision and reveal obey lifecycle gates',async()=>{
  const store=new Store(':memory:');store.ingestBatch([{platform:'youtube',channel:'c',author:'u',name:'Viewer',text:'hello'}]);
  const generator:PersonaGenerator=async(request)=>({definition:fixtureDefinition(request)});const model=async(input:any)=>({decision:{action:'skip',text:null,replyToMessageId:null,evidenceFrameIds:[],evidenceMessageIds:[],evidenceTranscriptIds:[]}});const service=new PersonaService(store,model as any,config,generator);const session=service.createBrief({session_title:'Lifecycle test',topic:'Puzzle game',audience_intent:'Observe',public_context:'Public context',private_production_context:'',tone_policy:'Natural',candidate_count:1,cast_size:1});
  const generated=await waitJob(service,service.createCandidates(session.id).id);const candidate=generated.result[0];
  const audition=service.audition(session.id,[candidate.id]);for(let i=0;i<100&&service.job(audition.id).status==='running';i++)await new Promise(r=>setTimeout(r,5));const evaluated=service.job(audition.id);assert.equal(evaluated.status,'succeeded');
  service.approve(candidate.id,{hash:candidate.hash,evaluation_id:audition.id,reviewer_decision:{approved:true,coherence:4,distinction:4,naturalness:4,relevance:4}});
  const cast=service.putCast(session.id,session.revision,[{version_id:candidate.id}]);const frozen=service.freeze(session.id,cast.revision,true);const live=service.start(session.id,frozen.revision,false);assert.equal(live.armed,false);
  const updated=service.updatePolicy(session.id,live.revision,{...live.policy,minimum_global_gap_ms:6000});assert.equal(updated.control_epoch,live.control_epoch+1);assert.throws(()=>service.arm(session.id,live.control_epoch));
  const armed=service.arm(session.id,updated.control_epoch);assert.equal(armed.armed,true);const member:any=armed.cast[0];store.beginPersonaAttempt({id:'attempt-1',sessionId:session.id,memberId:member.member_id,eventIds:[],cutoff:store.lastSeq(),sessionEpoch:armed.control_epoch,memberEpoch:member.epoch,definitionHash:member.definition_hash,configRevision:armed.revision});store.finishPersonaAttempt('attempt-1','candidate',null,{text:'A provider-generated viewer contribution'});assert.equal(store.personaCanPublish(session.id,member.member_id,armed.control_epoch,member.epoch,'attempt-1'),true);const messageId=store.publishPersona({attemptId:'attempt-1',memberId:member.member_id,name:member.display_name,text:'A provider-generated viewer contribution',replyToId:null});assert.ok(messageId);const publicMessage=store.readerSnapshot().messages.find(m=>m?.id===messageId)!;assert.equal(publicMessage?.attribution,'mixed');assert.match(publicMessage?.displayName??'',/^시청자-[a-f0-9]{8}$/);assert.equal(JSON.stringify(publicMessage).includes(member.member_id),false);
  store.beginPersonaAttempt({id:'attempt-2',sessionId:session.id,memberId:member.member_id,eventIds:[],cutoff:store.lastSeq()+1,sessionEpoch:armed.control_epoch,memberEpoch:member.epoch,definitionHash:member.definition_hash,configRevision:armed.revision});store.finishPersonaAttempt('attempt-2','candidate',null,{text:'A second generated contribution'});service.stop(session.id);assert.equal(store.personaCanPublish(session.id,member.member_id,armed.control_epoch,member.epoch,'attempt-2'),false);assert.equal(store.publishPersona({attemptId:'attempt-2',memberId:member.member_id,name:member.display_name,text:'A second generated contribution',replyToId:null}),null);assert.equal(service.getSession(session.id).armed,false);assert.equal(service.reveal(session.id,true).revealed,true);
  store.close();
});

test('persona retention purges expired session data even without old chat rows',()=>{
  const store=new Store(':memory:');const service=new PersonaService(store,undefined,config,async()=>{throw Error('unused');});const session=service.createBrief({session_title:'Expired',topic:'Topic',audience_intent:'Observe',public_context:'',private_production_context:'SECRET-CONTEXT',tone_policy:'Natural',candidate_count:1,cast_size:1});service.denyNickname(session.id,'BlockedName','operator request');store.db.prepare("UPDATE persona_sessions SET state='ended',updated=0 WHERE id=?").run(session.id);store.purge(Date.now());assert.equal(store.db.prepare('SELECT 1 FROM persona_sessions WHERE id=?').get(session.id),undefined);assert.equal(store.db.prepare('SELECT 1 FROM persona_name_denylist WHERE session_id=?').get(session.id),undefined);store.close();
});
